### ISSUE TITLE
Julia stops when specific operator is build

### ISSUE THREAD

**Issue by PhilippAumann** [qojulia/QuantumOptics.jl#178]
I ran into an interesting issue. When creating a specific operator Julia stops and returns 
> Julia has stopped: null, SIGKILL

Here is a minimal code that produces this error for me:

```julia
using QuantumOptics

systemsize = 5

b = NLevelBasis(systemsize)
b_mb = ManyBodyBasis(b, bosonstates(b,systemsize))
b_total = tensor(fill(b_mb,systemsize)...)

KetSite(j) = basisstate(b_mb,j)

ProjectionOperator(i,j) = embed(b_total, i, projector(KetSite(j)))

ProjectionOperator(1,1)
```

Changing "systemsize" to '1' in the definition of b_mb seems to resolve the problem (which is enough for my calculations)

**Comment by david-pl** [comment]
Looking at your code, it is clear that the system size you chose leads to a ridiculous dimension. I am not surprised at all that Julia crashes.

Looking at `b_total.shape` we see that the total dimension of the composite space is
```julia
julia> dim = prod(b_total.shape)
31757969376
```
Since you are using the `projector` function (which returns a `DenseOperator`) to build your operator, you are trying to build a matrix `dim^2` complex floats as entries. A complex float uses 16 bytes, meaning that this
```julia
julia> dim*16*1e-9
508.12751001600003
```
is the amount of GB ram you would require to even store one column of the created operator.

In general, I recommend you stick to `SparseOperator` types for large systems (e.g. by using `sparse(projector(KetSite(j)))`), but even that won't help for your current choice of dimensions. The only thing left to do is what you already did, namely reducing the `systemsize` parameter.
