### ISSUE TITLE
steadystate.master error

### ISSUE THREAD

**Issue by eunjongkim** [qojulia/QuantumOptics.jl#182]
Hi, I'm trying to run a simulation which will give steady-state polarization of a two-atom system driven by classical field, in presence of correlated decay. I was trying to run `steadystate.master` but it seems to be broken..

The time-evolution using `timeevolution.master` seems to give proper result:
```
tspan = 0.0:1e-10:2e-6
rho0 = tensor(basisstate(H.basis_l, 1), dagger(basisstate(H.basis_r, 1)))

@time tout, rho_t = timeevolution.master(tspan, rho0, H, σge; rates=γ_mat);
```
![image](https://user-images.githubusercontent.com/8111538/34367614-a84e309e-ea61-11e7-8d8a-cc81d3f24052.png)

![image](https://user-images.githubusercontent.com/8111538/34367619-bf1d8400-ea61-11e7-9493-4565a9e71d9d.png)

This means that tracedistance from the initial state converges, approaching the steady state.

However, when I try using steadystate, the first error I encounter is:
![image](https://user-images.githubusercontent.com/8111538/34367666-387dbb08-ea62-11e7-9d22-5d9bf8e499df.png)

I tried lowering `hmin` values to `1e-10`  by 
```
@time rho_ss = steadystate.master(H, σge; rates=γ_mat, hmin=1e-10)
```
it runs without error, but the job seems to be running forever. Would you mind looking at `steadystate.master` to check if there's any bug?

Thanks in advance.

**Comment by david-pl** [comment]
Hi there!

First off, the `hmin` error you get is caused by the default value of `steadystate.master` which sets it to `1e-7`. In the usual master equation `hmin` is chosen according to the provided list of times,
https://github.com/qojulia/QuantumOptics.jl/blob/b2f376bbd65333425b189f39b79cabc314a1e018/src/ode_dopri.jl#L356
which in your case results in about `2e-15`.

As for the large amount of time it takes for the steadystate function to solve the problem, this might be caused by the default accuracy being too high. Try changing the kwarg `eps` above its default value of `1e-3`. Additionally, `steadystate.master` calculates the tracedistance between `rho(t)` and `rho(t+dt)` at every step, which will also slow it down a bit.

How large is your Hilbert space dimension? For only two atoms it might be best to simply diagonalize the Liouvillian by using `steadystate.eigenvector`. Note, though, that there is currently no implementation of this for correlated decay, so you would have to use the `diagonaljumps` function as a workaround.

I hope this resolves the issue for you.
