### ISSUE TITLE
embed with false indexing overwrites sub-basis

### ISSUE THREAD

**Issue by david-pl** [qojulia/QuantumOptics.jl#240]
This bit of code
```julia
using QuantumOptics
bf = FockBasis(5)
bs = SpinBasis(1//2)
σ = sigmam(bs)

embed(bf⊗bs,1,σ)
```
results in
```julia
SparseOperator(dim=4x4)
  basis: [Spin(1/2) ⊗ Spin(1/2)]
  [2, 1]  =  1.0+0.0im
  [4, 3]  =  1.0+0.0im
```
which clearly overwrites the `FockBasis`. This should throw an error.

**Comment by atombear** [comment]
trying to 'fix' this i think there is a deeper bug: in `testing_operators.jl` `embed(b, 1, op)` returns a 45x45 array, where it should not. the reason is that it tries to embed the 15x15 op in the 5x5 space, leaving a 3x3 identity. this functionality is missing: operators cannot be properly embedded in a joint hilbert space of a CompositeBasis. i think the call should be `embed(b, [1, 2], op)`.

**Comment by david-pl** [comment]
Thanks for the PR and I agree with the syntax change. This also leads to the question of combining operators on composite bases with ones on single ones, which unfortunately isn't that straightforward. I'm looking into it.

**Comment by atombear** [comment]
i have taken the opportunity to do the index wrangling in this pr. please tell me if you want me to make separate prs, or if i'm totally off base.

**Comment by atombear** [comment]
i've provided what i think is a feature complete solution for embedding, though the syntax leaves something to be desired. x86 tests are failing, i don't know why. please tell me if this is an acceptable solution.
