### ISSUE TITLE
Jump times and operators

### ISSUE THREAD

**Issue by ngedwin98** [qojulia/QuantumOptics.jl#247]
When simulating quantum trajectories via `mcwf` (or similar), is there a recommended way using the API to access 1) the times at which a jump occurs, and 2) which jump operator caused the jump? (That is, the equivalent of `Result.col_times` and `Result.col_which` in [QuTiP](http://qutip.org/docs/4.0.2/apidoc/classes.html#Result.col_times), respectively.)

I imagine it might be possible to obtain the jump times by passing `fout(t,psi) = t` and then using `display_beforeevent=true`, but would there be any ambiguity to doing the same thing but with `display_afterevent=true`? Additionally, I still don't see a way to obtain *which* operator caused the jump without diving a little deeper into the DiffEq backend.

Any tips or workarounds would be appreciated.

**Comment by david-pl** [comment]
1) As you say, you can obtain the times at which a jump occurs by setting either `display_beforeevent=true` or `display_afterevent=true`. Setting both will simply give you the same time twice. Note, however, that it's not necessary to specify an `fout` to obtain the times, as these are always returned separately. The saving times are controlled by the list of times you pass, so if you do something like
```julia
tout, psi = timeevolution.mcwf([0.0,10.0],psi0,H,J; display_beforeevent=true)
```
then `tout[2:end-1]` contains the times of the jumps. `psi[2:end-1]` will contain the states just before a jump occurs.

2) Finding the operators with which a jump is performed is not so trivial, unfortunately. I see why this can be useful sometimes (never needed it so far though), so we should actually add this feature. For now, you can use this "ugly" workaround:
Set both `display_beforeevent=true` and `display_afterevent=true`, and save only at these points like before,
```julia
tout, psi = timeevolution.mcwf([0.0,10.0],psi0,H,J; display_beforeevent=true,display_afterevent=true)
```
Now `tout` will contain the times of the jumps twice. Additionally, you have the states just before and after the jumps. As it says in the [documentation](https://qojulia.org/documentation/timeevolution/mcwf.html), the state after the jump is obtained by applying the jump operator and renormalizing. So applying each jump operator to the state before the jump gives the maximal overlap with the state after the jump if you have the correct jump operator. In code:
```julia
jump_ops = []
for i=2:length(tout)-1
    if tout[i] == tout[i+1]
        overlap = [abs2(dagger(psi[i+1]) * normalize(j * psi[i])) for j=J]
        index = findmax(overlap)[2]
        push!(jump_ops, J[index])
    end
end
```
**Note**: Thanks to your issue, I actually noticed a bug with the event displaying. The state was saved before being updated with `display_afterevent=true`, so one actually got the state before the jump. The above workaround doesn't work with the current version due to this. So you'll have to wait until I merged the according patch [here](https://github.com/qojulia/QuantumOptics.jl/tree/mcwf-display-bug) (which I'll do right after the tests pass).

I'll leave this issue open until we add a nicer way to find the operators, e.g. a new kwarg like `display_which` or so.

**Comment by david-pl** [comment]
I finally got around to doing this. One can now set the `display_jumps=true` kwarg like so:
```julia
tout, psi, t_jumps, j_ind = timeevolution.mcwf([0.0,10.0],psi0,H,J; display_jumps=true)
```
to obtain a list of times `t_jumps` corresponding to the times at which the jumps occur. `j_ind` is then a list of indexes corresponding to the indexes of `J`, with which each jump occurred.
