### ISSUE TITLE
Unitary time-evolution operator

### ISSUE THREAD

**Issue by seadra** [qojulia/QuantumOptics.jl#274]
It'd be nice to have a solver which can calculate the unitary time-evolution operator which also obeys the Schroedinger equation i \hbar U'(t) = H(t) U(t)

**Comment by alastair-marshall** [comment]
I agree, I can try to write one that works with the other time evolution solvers

**Comment by david-pl** [comment]
> the only issue is that we essentially want psi to not be a Ket... right?

Right! We could loosen the type constraints of the required functions, or add another dispatch for operators.

**Comment by alastair-marshall** [comment]
I guess we don't want to loosen the constraints since depending on whether the input is of type `Ket` or `Bra` we order them in the evolution differently so another dispatch would make more sense.

There are two potential ways I can see this working, I don't know which is better.

1. Another definition of `function schroedinger` where instead of `psi0::T` we have some `U0::T` where T is Operator
2. Open up `function schroedinger` so that `psi0::T` is {Operator, StateVector}

In both cases we dispatch to:

```julia
function dschroedinger(U0::AbstractOperator{B, B}, H::AbstractOperator{B,B}, dU::AbstractOperator{B, B}) where B<:Basis
    QuantumOpticsBase.mul!(dU,H,U0,eltype(U0)(-im),zero(eltype(U0)))
    return dU
end


```

**Comment by david-pl** [comment]
What I meant was loosing the type constraints on the dispatch for `Ket` only, which would leave the dispatch to `Bra` unchanged. But yes, another dispatch makes sense.

I would go with 2. suggestion, setting `T<:Union{Operator,StateVector}` since otherwise you essentially copy-paste the entire function. The same goes for `schroedinger_dynamic`. Note that you will have to replace things like this https://github.com/qojulia/QuantumOptics.jl/blob/6a90f3a68545fe973059382396e4a9f276e9a6ce/src/schroedinger.jl#L21 with `state=copy(psi0)`. The rest should be fine I think.

**Comment by alastair-marshall** [comment]
Ah! I didn't see that was a suggestion, I'll do that then and open the dispatch on Ket to operators too.

**Comment by david-pl** [comment]
Added with #275
