### ISSUE TITLE
WARNING: Interrupted. Larger maxiters is needed

### ISSUE THREAD

**Issue by Haohun** [qojulia/QuantumOptics.jl#276]
The method of `timecorrelations.correlation` to caculate the correlation fuctions, if I set the timelist large, there will be a warning that
 _Interrupted. Larger maxiters is needed_

PS: For example, as discussed in the link, [https://github.com/qojulia/QuantumOptics.jl-examples/blob/master/notebooks/correlation-spectrum.ipynb]
if I chage the time list
`dτ = 0.05
τmax = 1000000
τ = [0:dτ:τmax;]
corr = timecorrelations.correlation(τ, ρ₀, H, J, dagger(a), a)`

How could I over come this problems? To set the τmax smaller? But, sometimes, this will lead the range of freqency get through `correlation2spectrum` smaller than I wanted.

**Comment by david-pl** [comment]
This isn't really surprising. The time you set is rather huge. I suppose numerical errors add up such that at some point the integrator used can no longer achieve the required accuracy within the number of iterations given by `maxiters`. Hence, the warning you receive.

A few options you can try to overcome this are:

- Try using larger tolerances (allowing for larger numerical error) by changing the keyword arguments `abstol` and `reltol`
- You can just do what the warning says and provide a larger `maxiters`. Note that this will slow the integration down.

For a list of options to set regarding the step-size, see the DifferentialEquations.jl documentation: https://diffeq.sciml.ai/latest/basics/common_solver_opts/#Stepsize-Control

Finally, you mention:
> But, sometimes, this will lead the range of freqency get through correlation2spectrum smaller than I wanted.

Note, that the time used when computing the `correlation` and the resulting frequency in the spectrum are connected by a Fourier transform. This means that the final time of the integration specifies the resolution of the frequency list `dω ∝ 1/τmax` whereas `dτ` controls the total range of the frequency, `ωmax ∝ 1/dτ`. So to obtain a larger range of frequency you actually need to decrease `dτ` rather than increase `τmax`.
