### ISSUE TITLE
LazyTensor abnormal allocs

### ISSUE THREAD

**Issue by Lightup1** [qojulia/QuantumOptics.jl#331]
When using LazyTensor, allocations of  the time evolution solver is abnormal.
What cause this? And when should we use LazyTensor?
![image](https://user-images.githubusercontent.com/32999017/163748332-613f455c-c1b4-4ce8-8cfb-5aba155e4426.png)

**Comment by ChristophHotter** [comment]
I think using lazy operations doesn't make much sense here. 

Usually they are used for the position and momentum basis, since the FFT is really fast to convert between these two and makes operators diagonal, which speeds up the calculation. See e.g.  [Particle in harmonic trap potential](https://docs.qojulia.org/examples/particle-in-harmonic-trap/#Particle-in-harmonic-trap-potential).

The `LazyTensor` is normally used if you have two position and momentum spaces.
This is described in the example [Dynamics of a two-dimensional wavepacket hitting a Gaussian potential](https://docs.qojulia.org/examples/wavepacket2D/#Dynamics-of-a-two-dimensional-wavepacket-hitting-a-Gaussian-potential).

**Comment by Lightup1** [comment]
OK, thanks for your help.
