### ISSUE TITLE
Can't see occupations for composite many-body basis 

### ISSUE THREAD

**Issue by Umut-Can-Physics** [qojulia/QuantumOptics.jl#383]
Example code is following:
```
b = NLevelBasis(3)
s = bosonstates(b, [0,1,2])
mb = ManyBodyBasis(b,s)
A = destroy(mb,1) ⊗ identityoperator(mb) # composite operator
A.basis_l # print: [ManyBody(onebodybasis=NLevel(N=3), states:10) ⊗ ManyBody(onebodybasis=NLevel(N=3), states:10)]
mb.occupations # one species basis # I can reach it
MB = tensor(mb,mb)
# But there is no occupations tag for MB object
MB.bases # (ManyBody(onebodybasis=NLevel(N=3), states:10), ManyBody(onebodybasis=NLevel(N=3), states:10))
MB.shape # 2-element Vector{Int64}: 10 10
```
So, ı want to see our occupations or Fock basis for composite mixture. I'm wondering how QoJulia construct basis for my `A` operator?

**Comment by Krastanov** [comment]
Hi, @Umut-Can-Physics ! Sorry for the long wait, the notification about this post got lost. Do not hesitate to bump posts in situations like this (e.g. by making a reminder comment; emoji reactions do not generate notifications so we probably would not see those).

As a rule of thumb, if you are accessing a field of a struct in julia, you are probably working with internal implementation details, not with a stable public API. Such implementation details can change without warning (they are not part of the public API which has stability guarantees). More specifically, you should avoid relying on `mb.occupations` and instead use `s` which you have already defined (partially because most bases do not even have `.occupations` defined for them).

To try to answer your questions though: I am not immediately sure what you want `MB.occupations` to be -- could you give an expected result or a definition?

One possible answer would be:
```
julia> s = bosonstates(3,[0,1,2]);
julia> [[a;b] for a in s for b in s]
```

Or if you just want to get all the basis states:
```
julia> [basisstate(MB, i) for i in 1:length(MB)]
```

**Comment by Umut-Can-Physics** [comment]
I solved that problem. Let say I wanna construct two body space via tensor product that compatible with operators where located at QoJulia freamwork such as `create(MB, 1) ` or `destroy(MB,1)`

To do that run the following code
`
OneComponentBasis = bosonstates(3,[0,1,2]);
[[ copy(β),copy(α) ] for α in OneComponentBasis for β in OneComponentBasis]
`
And it return a set of basis as type of `element Vector{Vector{Vector{Int64}}}`
`
...
 [[1, 1, 0] ⊗ [0, 0, 0]]
...
`

**Comment by Krastanov** [comment]
Thanks for posting the resolution! I will close the issue for now, but feel free to reopen it (or to open a new one) if there is something else to figure out.
